# Generated by Django 5.0.6 on 2024-05-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('sender', models.CharField(max_length=200)),
                ('time_sent', models.TimeField(auto_now=True)),
            ],
        ),
    ]
