# Generated by Django 5.0.6 on 2024-05-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='name',
        ),
        migrations.AddField(
            model_name='drinks',
            name='drink',
            field=models.CharField(default='lemon', max_length=200),
        ),
        migrations.AddField(
            model_name='drinks',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
