# Generated by Django 5.0.6 on 2024-05-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='prince',
            new_name='price',
        ),
    ]
