# Generated by Django 5.0.6 on 2024-05-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='course',
            new_name='category',
        ),
    ]
