# Generated by Django 5.0.6 on 2024-05-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='Person_name',
        ),
    ]
